/**********************************************************************
Author: Prathamesh Nemade											  *	
                                                                      *
Decription: SQL script to create a table -  Note: DROPS first         *
SHIFTS_TYPE_MASTER, GUEST, STUDENT, RESIDENT                          *                            
This is the first script to run.                                      *
																	  *				
Date Created: 23/11/21 - 24/11/21                                     *
***********************************************************************/


DROP TABLE shifts_type_master;
DROP TABLE student;
DROP TABLE guest;
DROP TABLE resident;

DROP SEQUENCE guest_seq;
DROP SEQUENCE student_seq;



/**********************************************************************
Author: Prathamesh Nemade											  *	
                                                                      *
Decription: Shifts_Type_Master Table creation                         *
Note: No references used.                                             *
																	  *				
Date Created: 23/11/21                                                *
***********************************************************************/
CREATE TABLE shifts_type_master (
    shift_type CHAR(4) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time   TIMESTAMP NOT NULL,
    CONSTRAINT shifts_type_master_pk PRIMARY KEY ( shift_type )
);


/**********************************************************************
Author: Prathamesh Nemade											  *	
                                                                      *
Decription: Student Table creation                                    *
Note: No references used.                                             *
																	  *				
Date Created: 23/11/21                                                *
***********************************************************************/
CREATE TABLE student (
    student_id        INTEGER NOT NULL,
    student_name      VARCHAR(50) NOT NULL,
    student_contact   VARCHAR(15) NOT NULL CHECK ( student_contact LIKE '(???)???-????' ),
    student_dob       DATE NOT NULL,
    student_gender    CHAR(1) NOT NULL CHECK ( student_gender = 'M'
                                            OR student_gender = 'F' ),
    is_resident       CHAR(5) DEFAULT 'FALSE' CHECK ( is_resident IN ( 'TRUE', 'FALSE' ) ),
    permanent_address VARCHAR2(320) NOT NULL,
    student_email     VARCHAR2(100) NOT NULL CHECK ( REGEXP_LIKE ( student_email,
                                                               '^(\S+)\@(\S+)\.(\S+)$' ) ),
    CONSTRAINT student_pk PRIMARY KEY ( student_id )
);


/**********************************************************************
Author: Prathamesh Nemade											  *	
                                                                      *
Decription: GUEST Table creation                                      *
Note: USE THIS BEFORE FOREIGN KEY REFERENCES TABLE                    *
																	  *				
Date Created: 24/11/21                                                *
***********************************************************************/
CREATE TABLE guest (
    guest_id      INTEGER NOT NULL,
    guest_name    VARCHAR(50) NOT NULL,
    guest_contact VARCHAR(15) NOT NULL CHECK ( guest_contact LIKE '(???)???-????' ),
    visit_date    TIMESTAMP NOT NULL,
    resident_id   INTEGER NOT NULL,
    CONSTRAINT guest_pk PRIMARY KEY ( guest_id ),
    CONSTRAINT guest_fk FOREIGN KEY ( resident_id )
        REFERENCES resident ( resident_id )
);




/**********************************************************************
Author: Prathamesh Nemade											  *	
                                                                      *
Decription: Resident Table creation                                   *
Note: DO NOT ADD THIS BEFORE ANY FOREIGN KEY REFERENCES               *
																	  *				
Date Created: 24/11/21                                                *
***********************************************************************/
CREATE TABLE resident (
    resident_id INTEGER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1
    NOT NULL,
    dorm_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    to_date DATE NOT NULL,
    from_date DATE NOT NULL,
    CONSTRAINT resident_pk PRIMARY KEY ( resident_id )
);


/**********************************************************************
Author: Prathamesh Nemade											  *	
                                                                      *
Decription: Sequences                                                 *
																	  *				
Date Created: 24/11/21                                                *
***********************************************************************/
CREATE SEQUENCE student_seq;
CREATE SEQUENCE guest_seq;


/**********************************************************************
Author: Prathamesh Nemade											  *	
                                                                      *
Decription: Triggers                                                 *
																	  *				
Date Created: 24/11/21                                                *
***********************************************************************/
CREATE OR REPLACE TRIGGER student_seq BEFORE
    INSERT ON student
    FOR EACH ROW
BEGIN
    SELECT
        student_seq.NEXTVAL
    INTO :new.student_id
    FROM
        dual;
END;


CREATE OR REPLACE TRIGGER guest_seq BEFORE
    INSERT ON guest
    FOR EACH ROW
BEGIN
    SELECT
        guest_seq.NEXTVAL
    INTO :new.guest_id
    FROM
        dual;
END;
